# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DoodleBears's Personal Website'
email: yangmufeng233@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Made by Codecademy's courses [Deploy Your Personal Git Website]
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://doodlebears.github.io/" # the base hostname & protocol for your site
twitter_username: 
github_username:  DoodleBears

# Build settings
markdown: kramdown
